### ISSUE TITLE
Coding standards package needs to be updated in composer

### ISSUE THREAD

**Issue by javigomez** [joomla-projects/jorobo#14]
Current composer links to old package 

<img width="885" alt="screen shot 2016-04-14 at 19 34 29" src="https://cloud.githubusercontent.com/assets/1375475/14537607/fb8d2838-0277-11e6-9e20-a664e46a4676.png">

cc: @nibra

**Comment by yvesh** [comment]
Removed the two packages and the metrics task for now, as it is causing issues with other dependencies.

@nibra feel free to add it again when the issues are resolved. Thanks!
