### ISSUE TITLE
Media file installation problem

### ISSUE THREAD

**Issue by chrisdavenport** [joomla-projects/jorobo#20]
Support for media files seems a bit weird at the moment.  I set up a src/administrator/components/com_name/media directory and used ##MEDIA_FILES## in the component XML and that works okay but only if I also have the exact same files in src/media/com_name.

Not sure how it's intended to work here.

**Comment by yvesh** [comment]
Hi Chris,
not sure if i can follow you. The media files should only be in:

/src/media/com_name

JoRobo does not support media / lang files in the component directory itself.

**Comment by yvesh** [comment]
@chrisdavenport Any more hints on this? Else i close for now :-)
