### ISSUE TITLE
Some problems with build language task

### ISSUE THREAD

**Issue by joomdonation** [joomla-projects/jorobo#45]
1. This method https://github.com/joomla-projects/jorobo/blob/develop/src/Tasks/Build/Language.php#L145 is not working OK with new language file format (because the language file does not contain language tag. So the file is com_weblinks.ini instead of en-GB.com_weblinks.ini in the past. To build weblinks package, I modified it quickly to:
```php
if (empty(glob($this->adminLangPath . "/*/" . $this->ext . "*.ini")))
		{
			$this->hasAdminLang = false;
		}

		if (empty(glob($this->frontLangPath . "/*/" . $this->ext . "*.ini")))
		{
			$this->hasFrontLang = false;
		}
```

2. This line also needs to be reviewed https://github.com/joomla-projects/jorobo/blob/develop/src/Tasks/Build/Language.php#L240. For my quick modification, I modified is to:

```php
if (substr($file, 0, 1) != '.' && strpos($file, $this->ext . ".") !== false)
```

It might work but it could cause potential issues which I am not aware of.

**Comment by HLeithner** [comment]
@joomdonation any you provide a fix?

**Comment by joomdonation** [comment]
@HLeithner Do we have someone who is familiar with this script? I don't understand how it works yet, so I'm unsure if I can provide the right fix

Also, I guess we will have to fix it in a backward compatible way, mean it should works with both old format and new format of language filename (works with both en-GB.com_weblinks.ini and com_weblinks.ini) ?

**Comment by HLeithner** [comment]
hopefully fixed all issues with https://github.com/joomla-projects/jorobo/pull/46

**Comment by joomdonation** [comment]
Fixed with https://github.com/joomla-projects/jorobo/pull/46
