### ISSUE TITLE
Package language file is missing

### ISSUE THREAD

**Issue by yvesh** [joomla-projects/jorobo#8]
For package deployment the pkg language file (e.g. en-GB.pkg_weblinks.sys.ini) is missing in the zip archive.

**Comment by mbabker** [comment]
Package extensions are unsupported in full.  The manifest is also not correctly parsed.  This basically prevents anyone from creating a releasable build package for weblinks right now, which the last release tag does not support PHP 7.  This needs to be a high priority item.

**Comment by yvesh** [comment]
Fixed by #13
